### ISSUE TITLE
[1.5.0] i.setConfig is not a function

### ISSUE THREAD

**Issue by syphernl** [maxwroc/battery-state-card#141]
**Describe the bug**

After updating to v1.5.0 my Battery State Card is broken and show an error in the frontend.

**How to reproduce**

Update from 1.4.2 to 1.5.0.

**Expected behavior**

No error.

**YAML configuration**
```yaml
type: 'custom:auto-entities'
show_empty: false
card:
  type: 'custom:battery-state-card'
  title: Battery Devices
  sort_by_level: asc
  collapse: 5
  bulk_rename:
    - from: '_battery_level'
      to: ''
    - from: '_battery'
      to: ''
filter:
  include:
    - domain: sensor
      entity_id: '*_battery'
    - domain: sensor
      entity_id: '*_battery_level'
    - device_class: battery
  exclude:
    - domain: automation
    - domain: script
    - domain: alert
    - domain: persistent_notification

```

**Screenshots**

**Version**

* Problematic version: v1.5.0. 
* Last good version: v1.4.2. 

Both on HA 0.116.0

**Comment by maxwroc** [comment]
Is this error persistent? Try to refresh the page / restart HA. 

Please paste here what you see in the browser dev console.

I'm on 0.116 as well and I cannot see such error.

**Comment by maxwroc** [comment]
Also on what device/browser are you on?

**Comment by syphernl** [comment]
Odd, it was pretty much persistent across refreshes, went away immediately when I downgraded. I now updated to 1.5.0 again and after a force-reload it seems to be working fine. 

Case closed I guess :)

**Comment by maxwroc** [comment]
yeah I saw something similar once in the past but similarly it was gone after the refresh
